name: "Repository Dispatch Event"
description: "Custom action to trigger workflow dispatch events"
author: "Diego Maroto"

branding:
  icon: "cpu"
  color: "blue"

inputs:
  token:
    description: "GitHub token with repo scope"
    default: ${{ github.token }}
  repository:
    description: "Repository to trigger the event in"
    default: ${{ github.repository }}
  event-type:
    description: "Type of event to trigger"
  client-payload:
    description: "JSON payload to send with the event"
    required: false
    default: "{}"

outputs:
  result:
    description: "Result of the action"

runs:
  using: "node20"
  main: "dist/index.js"
